[2025-09-08T17:02:07.172+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T17:02:07.182+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskC scheduled__2025-09-05T00:00:00+00:00 [queued]>
[2025-09-08T17:02:07.187+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskC scheduled__2025-09-05T00:00:00+00:00 [queued]>
[2025-09-08T17:02:07.187+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T17:02:07.200+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): taskC> on 2025-09-05 00:00:00+00:00
[2025-09-08T17:02:07.203+0000] {standard_task_runner.py:72} INFO - Started process 16483 to run task
[2025-09-08T17:02:07.205+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskC', 'scheduled__2025-09-05T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmp9hbwin65']
[2025-09-08T17:02:07.207+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask taskC
[2025-09-08T17:02:07.233+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskC scheduled__2025-09-05T00:00:00+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T17:02:07.280+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-05T00:00:00+00:00'
[2025-09-08T17:02:07.280+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T17:02:07.291+0000] {logging_mixin.py:190} INFO - TASK C executed!
[2025-09-08T17:02:07.291+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-09-08T17:02:07.296+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T17:02:07.296+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskC, run_id=scheduled__2025-09-05T00:00:00+00:00, execution_date=20250905T000000, start_date=20250908T170207, end_date=20250908T170207
[2025-09-08T17:02:07.339+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-08T17:02:07.351+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-08T17:02:07.355+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
