[2025-09-08T17:08:06.908+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T17:08:06.915+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskA backfill__2025-04-05T00:00:00+00:00 [queued]>
[2025-09-08T17:08:06.919+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskA backfill__2025-04-05T00:00:00+00:00 [queued]>
[2025-09-08T17:08:06.919+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T17:08:06.930+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): taskA> on 2025-04-05 00:00:00+00:00
[2025-09-08T17:08:06.933+0000] {standard_task_runner.py:72} INFO - Started process 19682 to run task
[2025-09-08T17:08:06.935+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskA', 'backfill__2025-04-05T00:00:00+00:00', '--job-id', '116', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpdidn_ri4']
[2025-09-08T17:08:06.937+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask taskA
[2025-09-08T17:08:06.966+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskA backfill__2025-04-05T00:00:00+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T17:08:07.010+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskA' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2025-04-05T00:00:00+00:00'
[2025-09-08T17:08:07.011+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T17:08:07.021+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-08T17:08:07.022+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo TASK A has executed!']
[2025-09-08T17:08:07.028+0000] {subprocess.py:86} INFO - Output:
[2025-09-08T17:08:07.029+0000] {subprocess.py:93} INFO - TASK A has executed!
[2025-09-08T17:08:07.030+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-08T17:08:07.043+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T17:08:07.043+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskA, run_id=backfill__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250908T170806, end_date=20250908T170807
[2025-09-08T17:08:07.069+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-08T17:08:07.086+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-08T17:08:07.090+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
