[2025-09-08T17:02:05.227+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T17:02:05.234+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-06T00:00:00+00:00 [queued]>
[2025-09-08T17:02:05.239+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-06T00:00:00+00:00 [queued]>
[2025-09-08T17:02:05.240+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T17:02:05.252+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-09-06 00:00:00+00:00
[2025-09-08T17:02:05.255+0000] {standard_task_runner.py:72} INFO - Started process 16472 to run task
[2025-09-08T17:02:05.258+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-09-06T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpudkp35ze']
[2025-09-08T17:02:05.259+0000] {standard_task_runner.py:105} INFO - Job 124: Subtask taskBranch
[2025-09-08T17:02:05.287+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-06T00:00:00+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T17:02:05.362+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T00:00:00+00:00'
[2025-09-08T17:02:05.363+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T17:02:05.373+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-09-08T17:02:05.377+0000] {python.py:240} INFO - Done. Returned value was: taskC
[2025-09-08T17:02:05.377+0000] {branch.py:38} INFO - Branch into taskC
[2025-09-08T17:02:05.377+0000] {skipmixin.py:230} INFO - Following branch {'taskC'}
[2025-09-08T17:02:05.381+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1)]
[2025-09-08T17:02:05.398+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T17:02:05.399+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-09-06T00:00:00+00:00, execution_date=20250906T000000, start_date=20250908T170205, end_date=20250908T170205
[2025-09-08T17:02:05.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-08T17:02:05.450+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-08T17:02:05.454+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-08T17:04:52.495+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T17:04:52.502+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-06T00:00:00+00:00 [queued]>
[2025-09-08T17:04:52.507+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-06T00:00:00+00:00 [queued]>
[2025-09-08T17:04:52.507+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T17:04:52.519+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-09-06 00:00:00+00:00
[2025-09-08T17:04:52.522+0000] {standard_task_runner.py:72} INFO - Started process 17818 to run task
[2025-09-08T17:04:52.524+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-09-06T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpfwhkntkj']
[2025-09-08T17:04:52.526+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask taskBranch
[2025-09-08T17:04:52.553+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-06T00:00:00+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T17:04:52.601+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T00:00:00+00:00'
[2025-09-08T17:04:52.601+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T17:04:52.612+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-09-08T17:04:52.615+0000] {python.py:240} INFO - Done. Returned value was: taskD
[2025-09-08T17:04:52.616+0000] {branch.py:38} INFO - Branch into taskD
[2025-09-08T17:04:52.616+0000] {skipmixin.py:230} INFO - Following branch {'taskD'}
[2025-09-08T17:04:52.620+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskC', -1), ('taskE', -1)]
[2025-09-08T17:04:52.640+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T17:04:52.640+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-09-06T00:00:00+00:00, execution_date=20250906T000000, start_date=20250908T170452, end_date=20250908T170452
[2025-09-08T17:04:52.657+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-08T17:04:52.671+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-08T17:04:52.676+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
